### ISSUE TITLE
Do projects get restarted upon push?

### ISSUE THREAD

**Issue by liamzebedee** [twitchyliquid64/pushtart#1]
Was going to convert all my projects to it. One of them is a Node.js one for example - is the old `startup.sh` killed and a new one started?

**Comment by twitchyliquid64** [comment]
Correct - the old startup process tree is killed, and the containing directory deleted.

**Comment by liamzebedee** [comment]
Sweet - mention too that the code is stateless then (stateless on the FS that is)
