### ISSUE TITLE
Change tartLogRoutine to simply flush all output (no buffering) 

### ISSUE THREAD

**Issue by liamzebedee** [twitchyliquid64/pushtart#2]
I can't tell if my deployment is working or not (I've just got a simple echo command) - this is probably due to the fact it reads in buffers of 4096 bytes -- it's possible in Go to actually not even use a Buffer at all, and simply "pipe" the Stdin to a struct that implements Write, which would simply write to the appropriate place.

Can link sample code

**Comment by liamzebedee** [comment]
https://github.com/liamzebedee/jogger/blob/master/jogger.go#L121

**Comment by liamzebedee** [comment]
Perhaps it'd be better to log stdout by default, rather than running --log-stdout yes

**Comment by twitchyliquid64** [comment]
There is no buffering of the stdout logging, you just need to turn it on as you have discovered.

I agree that the default should be true for logging stdout - in retrospect I don't have any tarts where logging is not enabled.

Expect a commit this evening.
